apiVersion: v1
kind: Service
metadata:
  namespace: n2
  name: redis-svc
  labels:
    name: redis-svc
spec:
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    name: redis-server