apiVersion: v1
kind: Service
metadata:
  namespace: n1
  name: nodeapp-svc
spec:
  type: NodePort
  selector:
    name: nodeapp
  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 30007