apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: n1
  name: nodeapp
spec:
  replicas: 1
  selector:
    matchLabels:
      name: nodeapp
  template:
    metadata:
      labels:
        name: nodeapp
    spec:
      containers:
      - name: nodeapp
        image: 11nehas/node-app
        ports:
          - containerPort: 8081
        imagePullPolicy: "Always"
        livenessProbe:
          initialDelaySeconds: 5
          timeoutSeconds: 1
          httpGet:
            path: / 
            port: 8081
        env:
          - name: redis_host
            value: redis-svc.n2.svc.cluster.local
        resources:
          requests:
            cpu: 50m
            memory: 256Mi
          limits:
            cpu: 100m
            memory: 512Mi
